name: Python Script Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      USER_AGENT: ${{ secrets.USER_AGENT }}
      USERNAME_REDDIT: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: pip install -r requirements.txt # If you have any dependencies

    - name: Run Python script
      run: python main.py # Replace with your script filename
