name: Python Script Workflow

on:
  schedule:
    - cron: '*/2 * * * *' # Set your desired cron schedule

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: pip install -r requirements.txt # If you have any dependencies

    - name: Run Python script
      run: python main.py # Replace with your script filename
